### ISSUE TITLE
cgroup fields on macOS detections

### ISSUE THREAD

**Issue by NACHOSWITHCHEESE** [chainguard-dev/osquery-defense-kit#161]
Hi, 
I've observed when attempting to execute certain detections through `osqueryi` as a test on macOS, I am running into errors regarding the `cgroup` fields that are in some detections billed as macOS and posix ones. A quick search tells me that the following detections are said to be operating on macOS but contain the `cgroup` field:  
`detection/collection/high-disk-bytes-written.sql` , `detection/discovery/unexpected-netutil-calls-macos.sql`, `detection/discovery/unexpected-netutil-calls-macos.sql`, `detection/evasion/name_path_mismatch.sql`, `detection/evasion/name_path_mismatch.sql`, `detection/execution/exotic-command-events-macos.sql` `detection/execution/exotic-commands-macos.sql`, `detection/execution/relative-exec-low-uid.sql`,  `detection/execution/sketchy-fetcher-events.sql`,  `detection/execution/sketchy-fetcher.sql`, `detection/execution/unexpected-osascript-calls.sql`, `detection/execution/unexpected-sysutils-macos.sql` , `detection/exfil/high_disk_bytes_read.sql` ,  `detection/initial_access/unexpected-shell-parents.sql`

Is this a cause for concern?
Thank you!

**Comment by tstromberg** [comment]
Not a cause for concern, but it does add to the spam. Thanks for fixing this with #164
